"""Model card (D8 / §14).

The card is the artifact a stranger reads first, so it states the central promise,
what was actually demonstrated, and what is excluded — in that order. It is
generated from the capability record and the test results, never hand-written.

Central promise (verbatim in every card):

> This model was produced from the documents named below. It reproduces only the
> behaviour its capability probe demonstrated; everything else is listed as an
> exclusion or reported UNKNOWN. No behaviour, citation, or approval appears here
> that was not observed.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from boardmodeler.domain.enums import ModelKind
from boardmodeler.domain.records import (
    BEHAVIOR_KEYS,
    DocumentRecord,
    ModelCapability,
    Requirement,
    TestCase,
    TestResult,
)

__all__ = ["CENTRAL_PROMISE", "ModelCardInputs", "model_card_markdown"]

CENTRAL_PROMISE = (
    "This model was produced from the documents named below. It reproduces only the behaviour "
    "its capability probe demonstrated; everything else is listed as an exclusion or reported "
    "UNKNOWN. No behaviour, citation, or approval appears here that was not observed."
)

_STATE_LABEL = {
    "supported": "supported (probe passed)",
    "unsupported": "not supported (declared exclusion or structurally impossible)",
    "unknown": "UNKNOWN (probe could not establish it)",
    "not_tested": "not tested (no probe, or a prerequisite was not established)",
}


@dataclass(frozen=True)
class ModelCardInputs:
    """Everything the card needs, already resolved by the caller."""

    model_id: str
    model_kind: ModelKind
    evidence_level: str
    source_model_hash: str
    requirements: Sequence[Requirement]
    capability: ModelCapability
    results: Sequence[TestResult]
    tests: Sequence[TestCase] = ()
    documents: Sequence[DocumentRecord] = ()
    parameters: Mapping[str, str] = None  # type: ignore[assignment]
    limitations: Sequence[str] = ()
    generated_utc: str = ""
    tool_version: str = ""
    simulator: str = ""
    reproduction: Sequence[str] = ()

    def __post_init__(self) -> None:
        if self.parameters is None:
            object.__setattr__(self, "parameters", {})


def _status_counts(results: Sequence[TestResult]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for result in results:
        counts[result.status.value] = counts.get(result.status.value, 0) + 1
    return counts


def model_card_markdown(inputs: ModelCardInputs) -> str:
    """Render the model card as Markdown."""
    lines: list[str] = []
    lines.append(f"# Model card — `{inputs.model_id}`")
    lines.append("")
    lines.append(f"> {CENTRAL_PROMISE}")
    lines.append("")

    lines.append("## What this model is")
    lines.append("")
    lines.append(f"- model id: `{inputs.model_id}`")
    lines.append(f"- kind: `{inputs.model_kind.value}`")
    lines.append(f"- evidence level: `{inputs.evidence_level}`")
    lines.append(f"- model artifact sha256: `{inputs.source_model_hash}`")
    if inputs.simulator:
        lines.append(f"- simulator: {inputs.simulator}")
    if inputs.generated_utc:
        lines.append(f"- card generated: {inputs.generated_utc}")
    if inputs.tool_version:
        lines.append(f"- generated by: BoardModeler {inputs.tool_version}")
    lines.append("")

    lines.append("## Behaviour that was demonstrated")
    lines.append("")
    lines.append("| behaviour | status | probe evidence |")
    lines.append("|---|---|---|")
    for key in BEHAVIOR_KEYS:
        state = inputs.capability.behaviors.get(key, "unknown")
        probe = next(
            (r for r in inputs.results if r.test_id == f"T_capability_{key}"),
            None,
        )
        evidence = probe.detail.replace("|", "/") if probe else "no probe recorded"
        lines.append(f"| `{key}` | {_STATE_LABEL.get(state, state)} | {evidence} |")
    lines.append("")

    if inputs.requirements:
        lines.append("## Requirements this model was built against")
        lines.append("")
        lines.append("| requirement | class | statement | citation |")
        lines.append("|---|---|---|---|")
        for requirement in inputs.requirements:
            citation = "verified" if requirement.citation_verified else "NOT VERIFIED"
            statement = requirement.statement.replace("|", "/")
            lines.append(
                f"| `{requirement.req_id}` | {requirement.req_class.value} | {statement} | {citation} |"
            )
        lines.append("")

    if inputs.tests:
        lines.append("## Tests executed")
        lines.append("")
        counts = _status_counts(inputs.results)
        lines.append(
            "Results by status: "
            + ", ".join(f"{status}={count}" for status, count in sorted(counts.items()))
        )
        lines.append("")
        lines.append("| test | scenario | expected | requirement(s) |")
        lines.append("|---|---|---|---|")
        for case in inputs.tests:
            lines.append(
                f"| `{case.test_id}` | `{case.scenario_id}` | {case.expected.kind} | "
                f"{', '.join(case.requirement_ids) or '-'} |"
            )
        lines.append("")

    lines.append("## Tested conditions")
    lines.append("")
    if inputs.parameters:
        for key, value in sorted(inputs.parameters.items()):
            lines.append(f"- {key} = {value}")
    else:
        lines.append("- (no parameters recorded)")
    lines.append("")

    lines.append("## Exclusions and unverified behaviour")
    lines.append("")
    for exclusion in inputs.capability.exclusions:
        lines.append(f"- {exclusion}")
    for key in BEHAVIOR_KEYS:
        state = inputs.capability.behaviors.get(key, "unknown")
        if state in ("unsupported", "unknown", "not_tested"):
            notes = [
                r.detail for r in inputs.results if r.test_id == f"T_capability_{key}" and r.detail
            ]
            lines.append(
                f"- `{key}`: {_STATE_LABEL.get(state, state)}. {notes[0] if notes else ''}"
            )
    for limitation in inputs.limitations:
        lines.append(f"- {limitation}")
    lines.append("")

    if inputs.documents:
        lines.append("## Provenance")
        lines.append("")
        for document in inputs.documents:
            lines.append(
                f"- `{document.doc_id}` — {document.title} ({document.doc_type}), revision "
                f"{document.revision or 'unknown'}, sha256 `{document.file_hash}`"
                + (f", source {document.source_url}" if document.source_url else "")
            )
            if not document.redistribution_allowed:
                lines.append(
                    "  - redistribution not permitted: this document is referenced, not copied"
                )
        lines.append("")

    if inputs.reproduction:
        lines.append("## How to reproduce")
        lines.append("")
        lines.append("```powershell")
        lines.extend(inputs.reproduction)
        lines.append("```")
        lines.append("")

    return "\n".join(lines)
