"""Document store tests.

The PDFs are generated by reportlab here, and hashes are recomputed with
hashlib rather than with the package's own helper, so the store cannot validate
itself with the code under test.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest
from pypdf import PdfWriter
from pypdf.errors import PyPdfError
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from boardmodeler.documents.store import DocumentStore, DocumentStoreError

# A vendor model is opaque binary; this stands in for an encrypted .sub file.
_OPAQUE_VENDOR_BYTES = b"<Binary File>\n\x00\x01 not a PDF at all \xff\xfe"


def _write_datasheet(path: Path) -> None:
    """Two-page synthetic datasheet with a metadata title and page labels."""
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.setTitle("Synthetic Buck Regulator Datasheet")
    sheet.addPageLabel(0, style="ARABIC", start=1)
    sheet.drawString(72, 700, "Absolute maximum input voltage 20 V")
    sheet.showPage()
    sheet.drawString(72, 700, "Recommended input voltage 4.5 V to 17 V")
    sheet.showPage()
    sheet.save()


def _write_untitled_sheet(path: Path, text: str) -> None:
    sheet = canvas.Canvas(str(path), pagesize=letter)
    sheet.drawString(72, 700, text)
    sheet.showPage()
    sheet.save()


def _strip_metadata(source: Path, target: Path) -> None:
    """Rewrite ``source`` without its /Info dictionary (reportlab defaults to "untitled")."""
    writer = PdfWriter()
    writer.append(str(source))
    with target.open("wb") as handle:
        writer.write(handle)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _add_datasheet(store: DocumentStore, source: Path, **overrides: object):
    arguments = {
        "doc_type": "datasheet",
        "provenance": "user_supplied",
        "classification": "public",
    }
    arguments.update(overrides)
    return store.add_file(source, **arguments)


def test_add_file_records_the_files_own_hash_pages_and_labels(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    store = DocumentStore(tmp_path / "project")

    record = _add_datasheet(store, source, classification="unknown")

    assert record.file_hash == _sha256(source)
    assert record.page_count == 2
    assert record.text_extraction == "embedded"
    assert record.page_labels == {0: "1", 1: "2"}
    assert record.title == "Synthetic Buck Regulator Datasheet"
    assert record.classification == "unknown"
    assert record.remote_inference_allowed is False
    assert record.redistribution_allowed is False
    assert record.doc_id.startswith(f"DOC_{record.file_hash[:12]}_")
    assert record.path == f"docs/files/{record.doc_id}-synthetic_regulator.pdf"


def test_stored_original_is_byte_identical(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    project = tmp_path / "project"
    store = DocumentStore(project)

    record = _add_datasheet(store, source)
    stored = store.original_path(record.doc_id)

    assert stored.is_file()
    assert stored.parent == project / "docs" / "files"
    assert stored.read_bytes() == source.read_bytes()
    assert _sha256(stored) == record.file_hash


def test_adding_the_same_file_twice_keeps_one_record_and_one_copy(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    project = tmp_path / "project"
    store = DocumentStore(project)

    first = _add_datasheet(store, source)
    second = _add_datasheet(store, source)

    assert second.doc_id == first.doc_id
    assert second == first
    assert store.records() == [first]
    stored_files = sorted(path.name for path in (project / "docs" / "files").iterdir())
    assert stored_files == [f"{first.doc_id}-synthetic_regulator.pdf"]
    assert sorted(path.name for path in (project / "docs").glob("*.json")) == [
        f"{first.doc_id}.json"
    ]


def test_doc_id_follows_the_content_not_the_call(tmp_path: Path) -> None:
    project = tmp_path / "project"
    store = DocumentStore(project)
    first_source = tmp_path / "first.pdf"
    _write_datasheet(first_source)
    second_source = tmp_path / "second.pdf"
    _write_untitled_sheet(second_source, "a different document entirely")

    first = _add_datasheet(store, first_source, title="Synthetic Buck Regulator Datasheet")
    repeated = _add_datasheet(store, first_source, title="Synthetic Buck Regulator Datasheet")
    different = _add_datasheet(store, second_source, title="Synthetic Buck Regulator Datasheet")

    assert repeated.doc_id == first.doc_id
    assert different.doc_id != first.doc_id
    assert different.file_hash != first.file_hash
    assert len(store.records()) == 2


def test_title_falls_back_to_the_file_name_when_the_document_has_none(tmp_path: Path) -> None:
    source = tmp_path / "unnamed_sheet.pdf"
    _write_untitled_sheet(source, "body text")
    without_title = tmp_path / "no_title.pdf"
    _strip_metadata(source, without_title)
    store = DocumentStore(tmp_path / "project")

    record = _add_datasheet(store, without_title)

    assert record.title == "no_title"
    assert record.title != "untitled"  # reportlab's default title is not a title


def test_re_adding_with_different_metadata_raises_instead_of_dropping_it(
    tmp_path: Path,
) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    store = DocumentStore(tmp_path / "project")
    _add_datasheet(store, source, classification="unknown")

    with pytest.raises(DocumentStoreError):
        _add_datasheet(store, source, classification="public")


def test_add_file_rejects_an_escaping_doc_id(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    project = tmp_path / "project"
    store = DocumentStore(project)

    with pytest.raises(ValueError):
        _add_datasheet(store, source, doc_id="../escaped")
    with pytest.raises(ValueError):
        _add_datasheet(store, source, doc_id="sub/dir")
    assert not (tmp_path / "escaped.json").exists()
    assert store.records() == []


def test_add_file_rejects_values_outside_the_record_vocabulary(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    store = DocumentStore(tmp_path / "project")

    with pytest.raises(ValueError):
        store.add_file(source, doc_type="datasheat", provenance="user_supplied")
    with pytest.raises(ValueError):
        store.add_file(source, doc_type="datasheet", provenance="probably_mine")
    with pytest.raises(ValueError):
        store.add_file(
            source,
            doc_type="datasheet",
            provenance="user_supplied",
            classification="secret",
        )


def test_add_file_requires_the_source_to_exist(tmp_path: Path) -> None:
    store = DocumentStore(tmp_path / "project")

    with pytest.raises(FileNotFoundError):
        _add_datasheet(store, tmp_path / "missing.pdf")


def test_vendor_model_is_stored_without_being_parsed(tmp_path: Path) -> None:
    binary = tmp_path / "vendor_part.sub"
    binary.write_bytes(_OPAQUE_VENDOR_BYTES)
    store = DocumentStore(tmp_path / "project")

    record = store.add_file(binary, doc_type="vendor_model", provenance="user_supplied")

    assert record.file_hash == _sha256(binary)
    assert record.page_count == 0
    assert record.text_extraction == "none"
    assert record.page_labels == {}
    assert record.title == "vendor_part"
    assert store.original_path(record.doc_id).read_bytes() == _OPAQUE_VENDOR_BYTES
    # Control: the same bytes really are not a PDF, so a parsed type must fail
    # rather than quietly store an empty inventory.
    with pytest.raises(PyPdfError):
        store.add_file(binary, doc_type="datasheet", provenance="user_supplied")


def test_add_synthetic_marks_the_fixture_public_and_local_only(tmp_path: Path) -> None:
    text = "PERST# must be held low until both rails are in regulation.\n"
    store = DocumentStore(tmp_path / "project")

    record = store.add_synthetic("switch contract", text)

    assert record.provenance == "synthetic_fixture"
    assert record.doc_type == "synthetic_contract"
    assert record.classification == "public"
    assert record.remote_inference_allowed is False
    assert record.redistribution_allowed is False
    assert record.file_hash == hashlib.sha256(text.encode("utf-8")).hexdigest()
    assert record.page_count == 1
    stored = store.original_path(record.doc_id)
    assert stored.suffix == ".txt"
    assert stored.read_text(encoding="utf-8") == text
    assert store.add_synthetic("switch contract", text) == record
    assert len(store.records()) == 1


def test_records_reload_from_disk_and_round_trip(tmp_path: Path) -> None:
    source = tmp_path / "synthetic_regulator.pdf"
    _write_datasheet(source)
    project = tmp_path / "project"
    store = DocumentStore(project)
    pdf_record = _add_datasheet(store, source)
    synthetic_record = store.add_synthetic("switch contract", "strap values are sampled late")

    reopened = DocumentStore(project)
    loaded = reopened.records()

    assert [record.doc_id for record in loaded] == sorted(
        [pdf_record.doc_id, synthetic_record.doc_id]
    )
    assert reopened.get(pdf_record.doc_id) == pdf_record
    assert reopened.get(pdf_record.doc_id).page_labels == {0: "1", 1: "2"}
    assert reopened.original_path(pdf_record.doc_id) == store.original_path(pdf_record.doc_id)
    assert reopened.original_path(synthetic_record.doc_id).exists()
    assert type(pdf_record).model_validate_json(pdf_record.model_dump_json(indent=2)) == pdf_record


def test_get_rejects_a_missing_or_impossible_id(tmp_path: Path) -> None:
    store = DocumentStore(tmp_path / "project")

    with pytest.raises(KeyError):
        store.get("DOC_000000000000_nothing_here")
    with pytest.raises(ValueError):
        store.get("../docs/DOC_x")
    assert store.records() == []
